In [ ]:
from IPython.core.display import HTML
HTML('''
<script>
var logoParent = document.getElementById("kernel_logo_widget")
var logo = document.getElementById("kernel_logo_widget").getElementsByClassName("current_kernel_logo")[0];
logo.src = "https://i.ibb.co/mD4jTGQ/itclogo.jpg";
logo.style = "display: inline; width:138px; height:40px";
logoParent.innerHTML = '<a href="https://i.ibb.co/mD4jTGQ/itclogo.jpg">' + logoParent.innerHTML + '</a>';
</script>
''')

<font size="36"><b>Numpy - Assignment II</b></font> <img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" height=200 width=200>

Based on questions from https://www.w3resource.com

In [ ]:
import numpy as np

# Question #1

Write a Python program to find the maximum and minimum value of a given flattened array.

In [30]:
import numpy as np
a = np.arange(4).reshape((2,2))

def find_min_max(flatt_arr):
    return 'in the array \n{}\n\n the minimum is: {},\n and the maximum is: {}'.format(flatt_arr,np.min(flatt_arr), np.max(flatt_arr))

print(find_min_max(a))

in the array 
[[0 1]
 [2 3]]

 the minimum is: 0,
 and the maximum is: 3


# Question #2

Write a function to calculate the difference between the maximum and the minimum values of a given array along the second axis, using NumPy

In [38]:
def difference (arr):
    return np.max(arr,axis=1) - np.min(arr,axis=1)
print(difference(a))

[1 1]


# Question #3

Write a function to compute the mean, standard deviation, and variance of a given array using NumPy. 
- Do each operation in two different ways, and check using NumPy's `allclose` function that the values are similar. 
- Use the function on an NumPy array of your choice.

In [71]:
x = a.copy()

def mean_std_var(arr):
    mean1 = np.mean(arr)
    mean2 = np.average(arr)
    assert np.allclose(mean1, mean2)
    
    std1 = np.std(arr)
    std2 = np.sqrt(np.mean((arr - np.mean(arr)) ** 2 ))
    assert np.allclose(std1, std2)
   
    var1= np.var(arr)
    var2 = np.mean((arr - np.mean(x)) ** 2 )
    assert np.allclose(var1, var2)

    return "\nOriginal array: \n\n{}\n\nmean: {}, std: {}, var: {}\n\n".format(arr,mean1, std1, var1)
    
print(mean_std_var(x))


Original array: 

[[0 1]
 [2 3]]

mean: 1.5, std: 1.118033988749895, var: 1.25




# Question #4

Write a NumPy program to test element-wise of a given array for finiteness (not positive / negative infinity and not Not a Number). 
- Return True is all members are finite, and False otherwise. 
- Use the function on an array of your choice.

In [104]:
x = np.array([-np.inf, 0., np.inf,np.nan, 1,-7])
y = np.arange(1,10)
print(x,'\n',y)
def testing_wise(arr):
    element_wise = ~(np.isneginf(arr)|np.isnan(arr)|np.isnan(arr)).any()
    return element_wise
print(testing_wise(x))
print(testing_wise(y))

[-inf   0.  inf  nan   1.  -7.] 
 [1 2 3 4 5 6 7 8 9]
False
True


# Question #5

Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [111]:
#Examples of a structured array:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), \
                    ('Pit', 5, 40.11)]
def structured_arr(data_type, students_details):
    students = np.array(students_details, dtype=data_type)
    sort_stud = np.sort(students, order='height')
    return sort_stud

print(structured_arr(data_type, students_details))
    
       

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


# Question #6

Given two arrays, write a python program that will stack the arrays in two ways:
- Stack the arrays on top of each other (final dimension 8x4)
- Stack them horizontally (final dimension 4x8)

In [115]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
print(np.vstack((a,b)),'\n\n')
print(np.hstack((a,b)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


# Question #7

Find a numpy function to limit the values of an array between two numbers. Use this function to limit the given array between 3 and 8

In [116]:
x = np.arange(10)
np.clip(x, 3,8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])

# Question #8

Convert the given array from floats to ints

In [123]:
x = np.ones(10)
x.astype(np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])